DEFAULT_CATEGORIES: list[tuple[str, str]] = [
    ("Food & Dining", "expense"),
    ("Groceries", "expense"),
    ("Rent", "expense"),
    ("Utilities", "expense"),
    ("Transportation", "expense"),
    ("Shopping", "expense"),
    ("Entertainment", "expense"),
    ("Subscriptions", "expense"),
    ("Healthcare", "expense"),
    ("Education", "expense"),
    ("Travel", "expense"),
    ("EMI / Loans", "expense"),
    ("Investments", "expense"),
    ("Salary / Income", "income"),
    ("Credit Card Payment", "transfer"),
    ("Wallet Transfer", "transfer"),
    ("Bank Transfer", "transfer"),
    ("Transfers", "transfer"),
    ("Other", "expense"),
]

CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "Food & Dining": ["zomato", "swiggy", "restaurant", "cafe", "coffee", "starbucks", "dominos"],
    "Groceries": ["bigbasket", "blinkit", "zepto", "dmart", "grocery", "more retail"],
    "Rent": ["rent", "landlord", "house owner"],
    "Utilities": ["electricity", "broadband", "wifi", "gas", "water bill", "mobile bill", "airtel", "jio"],
    "Transportation": ["uber", "ola", "rapido", "metro", "fuel", "petrol", "irctc"],
    "Shopping": ["amazon", "flipkart", "myntra", "nykaa", "ajio", "shopping"],
    "Entertainment": ["bookmyshow", "pvr", "inox", "gaming"],
    "Subscriptions": ["netflix", "spotify", "prime", "hotstar", "youtube premium", "icloud", "google one"],
    "Healthcare": ["pharmacy", "apollo", "hospital", "doctor", "1mg", "pharmeasy"],
    "Education": ["course", "udemy", "coursera", "college", "school"],
    "Travel": ["hotel", "makemytrip", "goibibo", "air india", "indigo"],
    "EMI / Loans": ["emi", "loan", "lending", "nbfc"],
    "Investments": ["zerodha", "groww", "mutual fund", "sip"],
    "Salary / Income": ["salary", "payroll", "stipend", "freelance payout"],
    "Credit Card Payment": ["credit card payment", "onecard payment", "card payment", "cc payment"],
    "Wallet Transfer": ["wallet load", "amazon pay balance", "phonepe wallet", "paytm wallet"],
    "Bank Transfer": ["self transfer", "neft", "imps", "rtgs"],
}

TRANSFER_KEYWORDS = [
    "credit card payment",
    "onecard payment",
    "wallet load",
    "self transfer",
    "transfer to own",
    "neft",
    "imps",
    "rtgs",
    "refund reversal",
]

